name: flutter_application_1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_cache_manager: ^3.3.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.2.2
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^0.13.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo_FlixPick.png
    - assets/images/icone_film.jpg